dist: trusty
sudo: false
language: cpp
install: export CXX="g++-6"

matrix:
  include:
      - env: CXX=g++-6 CC=gcc-6 GCOV=gcov-6
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - g++-6

before_install:
  - pip install --user cpp-coveralls

before_script:
  - mkdir build
  - cd build
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 GCOV=gcov-6 cmake -DCOVERAGE=1 ..

script: 
  - make 
  - make run_tests

after_success:
- coveralls --root . -E ".*CMakeFiles.*" 

notifications:
  email:
    recipients:
      - tino.bog@gmail.com
    on_success: change
    on_failure: always
