language: cpp
compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++5
- export CXX="g++-5"

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make run_tests

notifications:
  email:
    recipients:
      - tino.bog@gmail.com
      - nils.zander@tum.de
    on_success: change
    on_failure: always
