dist: trusty
sudo: require
language: cpp

matrix:
  include:
      - env: GCC_VERSION=6 CXX=g++-6 CC=gcc-6 GCOV=gcov-6
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - g++-6

before_install:
  - sudo pip install codecov

install:
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

before_script:
  - mkdir build
  - cd build
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 GCOV=gcov-6 cmake -DCOVERAGE=1 ..

script: 
  - make 
  - make run_tests
  - ./get_coverage
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
 
notifications:
  email:
    recipients:
      - tino.bog@gmail.com
    on_success: change
    on_failure: always
