dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-6
      - clang-5.0

before_install:
  - pip install --user cpp-coveralls

before_script:
  - mkdir build
  - cd build
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake -DCOVERAGE=1 ..

script: 
  - make 
  - make run_tests

notifications:
  email:
    recipients:
      - tino.bog@gmail.com
      - nils.zander@tum.de
    on_success: change
    on_failure: always
